In [15]:
import pandas as pd

df = pd.read_excel("Mapeamento de APTs - BBTS e BBA.xlsx", sheet_name='BBTS')
display(df)

          Finance Public Administration        Information
0       admin@338                 APT12              APT12
1           APT19                 APT18              APT17
2           APT38                 APT38              APT18
3           APT41         Aquatic Panda              APT19
4        Carbanak                 Axiom              APT41
5    Cobalt Group               Cleaver      Aquatic Panda
6      Deep Panda                CURIUM   Blue Mockingbird
7        Equation          Dark Caracal       Dark Caracal
8         Evilnum            Deep Panda         Deep Panda
9           FIN13             Dragonfly           DragonOK
10          GCMAN              DragonOK          Elderwood
11  Indrik Spider              Equation           Equation
12       menuPass         Indrik Spider        EXOTIC LILY
13         OilRig             Ke3change    GOLD SOUTHFIELD
14          Rocke         Lazarus Group      Indrik Spider
15  Sandworm Team               Machete            LAPSUS$
16          TA505              menuPass      Lazarus Group
17        TeamTNT         Mustang Panda            Machete
18            NaN                OilRig           menuPass
19            NaN            PittyTiger             OilRig
20            NaN        Poseidon Group         PittyTiger
21            NaN         Sandworm Team     Poseidon Group
22            NaN      Silent Librarian    ScatteredSpider
23            NaN                SowBug   Silent Librarian
24            NaN                 Turla      SilverTerrier
25            NaN        Volatile Cedar  Threat Group-1314
26            NaN                   NaN              Turla
27            NaN                   NaN            Windigo
28            NaN                   NaN      Wizard Spider